---
anticlick: "true"
clickkick: "§fVous avez été §6détecté§f par l'anticheat pour §6AUTOCLICK\n§fSi cela est une erreur reconnectez vous."
cpslimit: "14"
antixray: "true"
xraykick: "§fVous avez été §6détecté§f par l'anticheat pour §6X-RAY\n§fSi cela est une erreur reconnectez vous."
orelimit: "15"
antifly: "true"
flykick: "§fVous avez été §6détecté§f par l'anticheat pour §6FLY\n§fSi cela est une erreur reconnectez vous."
antikb: "true"
kbkick: "§fVous avez été §6détecté§f par l'anticheat pour §6KNOCKBACK\n§fSi cela est une erreur reconnectez vous."
#permission is fly.bypass
...
